### ISSUE TITLE
Could you help me extract from Triangle Love -アプリコットフィズ-?

### ISSUE THREAD

**Issue by mymzc4njm** [Dir-A/MalieTools#1]
Triangle Love -アプリコットフィズ-
https://vndb.org/v19445
Campus
malie engine
.dat file

Hello.
Could you help me extract from Triangle Love?
GARbro, exdieslib, exdieslib_mod doesn't work...

**Comment by Dir-A** [comment]
check this -> https://github.com/Dir-A/MalieTools/releases/tag/1.1
