### ISSUE TITLE
Need help extracting Silverio VNs and Magatsu Barai files

### ISSUE THREAD

**Issue by YoxalLoyal** [Dir-A/MalieTools#2]
Hello. Could you help me in opening the .dat files for the Silverio vns and Magatsu Barai? They use the new Malie engine so GarBRO is unable to open them.

Games: Silverio Vendetta -Verse of Orpheus- (https://vndb.org/r44979), Silverio Trinity -Beyond the Horizon- (https://vndb.org/r72689), Silverio Ragnarok (https://vndb.org/v26785) and Magatsu Barai (https://vndb.org/v32310)
Developer: light
Engine: Malie
File type: .DAT

**Comment by Dir-A** [comment]
I don't have the files for those games. If you can provide the files, I can try

**Comment by YoxalLoyal** [comment]
I have Ragnarok's files here: https://drive.google.com/drive/folders/1VZW8kjhUCUlRQkhWxb_XXUU0NqyZfFhF?usp=share_link

I will send you the files for Vendetta and Trinity later today as well. Don't have Magatsu Barai's so I guess we can skip that one. Thanks.

**Comment by Dir-A** [comment]
@YoxalLoyal Bro, I think you should upload the complete game file, otherwise I have no way to debug the game

**Comment by YoxalLoyal** [comment]
Okay, I uploaded everything in the game’s folder. You can try now.

**Comment by YoxalLoyal** [comment]
Hello again. Here are the files for Silverio Vendetta and Trinity. Thanks again.

Vendetta -Verse of Orpheus-: https://drive.google.com/drive/folders/1GmZtkzEAKL2ZbND-WXt61E_Rh71uE-Te?usp=share_link
Trinity -Beyond the Horizon-: https://drive.google.com/drive/folders/1orqHdkSQ5MIZ2gNcDK98phUrB2dBtcjz?usp=share_link

**Comment by Dir-A** [comment]
I have completed **Silverio Ragnarok** and **Silverio Vendetta -Verse of Orpheus-**.
But **Silverio Trinity -Beyond the Horizon-** I don't have google drive permission to access

**Comment by YoxalLoyal** [comment]
Sorry about that. I have changed the permission settings. You can try now.
https://drive.google.com/drive/folders/1orqHdkSQ5MIZ2gNcDK98phUrB2dBtcjz?usp=share_link

**Comment by Dir-A** [comment]
It's done.
but there's something wrong with the data2.dat of Silverio Vendetta -Verse of Orpheus-.
I'm not sure if it's a bug in exdieslib or if data2.dat is damaged during upload or download.
I've never seen this bug befor.

[exdieslib_mod.zip](https://github.com/Dir-A/MalieTools/files/11300499/exdieslib_mod.zip)

**Comment by YoxalLoyal** [comment]
Thank you. I'll try to reinstall Silverio Vendetta later today and resend you the files to try again.

Is there a way for me to use the modded exdieslib with GarBRO or do I use it as it is?

**Comment by Dir-A** [comment]
@YoxalLoyal 
Garbro actually supports the new version of decryption as well.
But Garbro's key import tool is not publicly available.
and I've never written C#, So I can't import the key directl.

The way to do it now is to run exdieslib and browse the resources with Garbro after the extraction is done

**Comment by YoxalLoyal** [comment]
Do you know how to combine the images together as they are fragmented. Not sure how with GarBRO.

**Comment by Dir-A** [comment]
1、Extract all Pack.
2、Use Garbro to browse files and open the file with the dzi suffix (image index).
3、Garbro will automatically merge images based on the information in dzi file，you can convert media with a right click.

**Comment by YoxalLoyal** [comment]
That works, thanks. Btw I redownloaded Vendetta. If the error is still there, then it's probably a Steam issue. Does it affect me extracting the character sprites and event cgs?
https://drive.google.com/drive/folders/1GmZtkzEAKL2ZbND-WXt61E_Rh71uE-Te?usp=share_link

**Comment by Dir-A** [comment]
https://github.com/Dir-A/MalieTools/releases/tag/1.2

Already fixed，try the new release.

**Comment by Cosetto** [comment]
@YoxalLoyal Either Rar or 7z can unpack Magatsu Barai, the password is **IrsysPack_CipherKey**

**Comment by Cosetto** [comment]
> @YoxalLoyal Garbro actually supports the new version of decryption as well. But Garbro's key import tool is not publicly available. and I've never written C#, So I can't import the key directl.
> 
> The way to do it now is to run exdieslib and browse the resources with Garbro after the extraction is done

Looks like we need to deserialize something [link](https://github.com/morkt/GARbro/issues/576#issue-1536016732)
And Crsky made a [tool](https://github.com/morkt/GARbro/issues/576#issue-1536016732) to import encryption's key to Formats.dat, but I'm sure how to use it

**Comment by Dir-A** [comment]
@Cosetto 
Just change the key in this place or have it read the key from an external file
https://github.com/morkt/GARbro/blob/master/ArcFormats/Malie/MalieEncryption.cs#L61

I do not write C#, can only do a little code changes, and do not have time to study C#-related framework.
So this difficult task should be left to others.

You can find the key in this place.
https://github.com/Dir-A/MalieTools/blob/main/MalieTools/Modules/MalieTools/CamelliaDecryption128_Key.h
https://github.com/Dir-A/MalieTools/blob/main/MalieTools/Modules/MalieTools/MalieDecryption_Key.h

**Comment by YoxalLoyal** [comment]
> @YoxalLoyal Either Rar or 7z can unpack Magatsu Barai, the password is **IrsysPack_CipherKey**

Thanks it works. Do you know of any programs that can work with the .pb and .json files to put the images together?

**Comment by Cosetto** [comment]
They belong to the game? Hm, I'm not sure though

**Comment by GIGAGAddfeffd** [comment]
> Hello again. Here are the files for Silverio Vendetta and Trinity. Thanks again.
> 
> Vendetta -Verse of Orpheus-: https://drive.google.com/drive/folders/1GmZtkzEAKL2ZbND-WXt61E_Rh71uE-Te?usp=share_link Trinity -Beyond the Horizon-: https://drive.google.com/drive/folders/1orqHdkSQ5MIZ2gNcDK98phUrB2dBtcjz?usp=share_link


в

**Comment by GIGAGAddfeffd** [comment]
> Hello again. Here are the files for Silverio Vendetta and Trinity. Thanks again.
> 
> Vendetta -Verse of Orpheus-: https://drive.google.com/drive/folders/1GmZtkzEAKL2ZbND-WXt61E_Rh71uE-Te?usp=share_link Trinity -Beyond the Horizon-: https://drive.google.com/drive/folders/1orqHdkSQ5MIZ2gNcDK98phUrB2dBtcjz?usp=share_link

Can u reploud this pls ?
