### ISSUE TITLE
Can you write a hook?

### ISSUE THREAD

**Issue by Aleisster** [Dir-A/MalieTools#3]
Can you make a hook to make the supported games reads the files without repack? The games can read "data" folder, but only when I delete all other datax.dat (and if it's a decrypted version in some games if i recall well). 
Also, would be possible to add support for ENG version of Dies irae ~Interview with Kaziklu Bey~ please? 
Here's a link to the game: https://drive.google.com/file/d/1oOYC-yyapFFZIYB8-x6Xr3Za3ECriFU6/view

**Comment by Dir-A** [comment]
I'll take a look at it when I have time.

**Comment by Cosetto** [comment]
You can check out this Malie packer [here](https://github.com/satan53x/SExtractor/tree/main/tools/Malie)
What you need to do is to fill the first 8 bytes of the original archive
![image](https://github.com/Dir-A/MalieTools/assets/81801486/2afd949c-3eb7-47f5-ab8c-752b97dd4376)
And the key from malie_database.json
You can create a patch archive, example: data3.dat, data4.dat, data5.dat, etc
I tested on Fuyu Uso and it works like a charm.
![image](https://github.com/Dir-A/MalieTools/assets/81801486/e3332e93-fcaa-4fb0-aa93-64c8472093b7)

**Comment by Cosetto** [comment]
> Dies irae ~Interview with Kaziklu Bey~

I add Dies irae Interview with Kaziklu Bey (Eng) in pull request, you can pack with the tool I mentioned above
![image](https://github.com/Dir-A/MalieTools/assets/81801486/ab8be6cf-c928-4fb0-a6db-ca5d0893adda)

**Comment by Akatsukidarkx** [comment]
> > Dies irae ~Interview with Kaziklu Bey~
> 
> I add Dies irae Interview with Kaziklu Bey (Eng) in pull request, you can pack with the tool I mentioned above ![image](https://private-user-images.githubusercontent.com/81801486/300262682-ab8be6cf-c928-4fb0-a6db-ca5d0893adda.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4MDMxOTQsIm5iZiI6MTcwNjgwMjg5NCwicGF0aCI6Ii84MTgwMTQ4Ni8zMDAyNjI2ODItYWI4YmU2Y2YtYzkyOC00ZmIwLWE2ZGItY2E1ZDA4OTNhZGRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDE1NTQ1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyOWZkMGM4Y2VkNDYyN2RkYzllMDQ5ZDBkMDQwZGYzMzZiOWJkYWIxYjlhYTE4OTgwOTYxMDM3MzUwOWRmNGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TVH2IBRXyz4OZorUQotwRWZ8kItBbk1YxQOlY5bimnM)
> 
> Alternative, you can use this [Formats.dat](https://github.com/satan53x/GARbro/releases/download/v1.5.44-d3/Formats_v240128.zip) and overwrite it on the old Formats.dat in GameData of [GARbro mod](https://github.com/crskycode/GARbro) Source: https://github.com/satan53x/GARbro/blob/master/SchemeTool/Program.cs

Good day, would it be possible to add compatibility in Garbro with "Soushuu Senshinkan Gakuen: Hachimyoujin -Ten no Toki- Regular Edition/PSVITA"? 

It happens that I can unpack it with "exdieslib_mod", but the extracted files cannot be displayed, for example PNGs, DZI, etc. It's as if they have some kind of encryption.

[https://mega.nz/folder/6ExwhJJR#c6um_lkmdsb7cDxRhyV4kA](url)

**Comment by Cosetto** [comment]
Yes, malie engine use encryption for different games. To extract resources from data.dat, we need keys, so we need to debug the game to get the keys (via game's exe). I don't know how to debug psvita games, really.
